os: linux
sudo: false
dist: trusty
language: java
jdk: oraclejdk8
cache:
  directories:
  - "~/.m2/repository"
before_install:
- bash .util/build_xatkit.sh
script:
- mvn install
notifications:
  slack:
    secure: mPHROW+o16WV0hlJW2nlIOQq+JvFivOPP0EBoYMXS9/yAd1lNXoD1tM+8AZBWbQ69dFAN2s/TVSgHaRTPPPlpuywDXdAgwDQ6uTdr8yVOLx16eH9u8hWDiO0G8neNKv6mwEe/xgTP4L6xJ+ElBdiqKhI+E7tzWdyxER1//uHD2CKXoKG43u9nI6JA3gV9ILirMGy495D9En9yihVm1QArlEbtQZRTl8/2vMrerSxp7xG35cei+uQZ2CA+pnpQ1wV/ea7n5eBNfFbKoMn70KR2lx0jSlAbl36PkpXxbiC2+YnBRrEZBEc1ZaujwsidiLvPo9NR4Byek7fQ1wK62en05YGtZGvHBEoG1R5qR9VThYBJrj4CkHdng5XCaN06aRKJKpW7n18NC+BVdM1MLLltRiLo/YZW62XHTQtUFcNkdKQHDGaNaST9TxeWIgosFWY291y+re4/fJM9Nut8r+m9FH/n+sxfAmGPmHm0gcYbTIYLBmRVhRoG5rhKukfRucna1hOv77VrzusCOHoqVxuYuAaakeO/7RtbkZE3s8NA3wLq7+vYUoL1WpXOFdPWSEPtryI5NM3NzNAi7kAJUALT/AmtkSWICJxSME3S41rX0U+sxjhdOO42knaIHMXp0Az2jeyK9Xaom/x6BiZNW85txvMSKf/0jguPD7lx5BQ5eI=
