os: linux
sudo: false
dist: trusty
language: java
jdk: oraclejdk8
cache:
  directories:
  - "~/.m2/repository"
before_install:
- bash .util/build_xatkit.sh
script:
- mvn install
notifications:
  slack:
    secure: Z97fPCfXn0typnkXIvbPFGcC3PJpdregkiDVVvODbCr8HP6SqIy4M+j0yu58QrozNX8MMBq8wasj9wgxqAAW8vtoOgpspTI2of1kJEV1eGTqw4xuiGJ0rj/PRpNDoNas/srqIHwBkfqPJ2Pw+Gk1BdKee84tK2rdLCNPI1FSJTy33sAnzIC0aLgE0RuoAgLyD0tDfFALhpU8uBpGDwT4BTJRv2fHTlw9Vch6DBjC2Wvj/aOmxB1k/ezPT98bLl8aGOqlCYowrAsBgt6nLzr1xDR+4SFVyidV7w9si4Z/R/OE9BOdYxN3u2v5RRjypQD/RV2pU1MeDPhzIMhj1Vx+o7dJ1Dhr+3vOEAQ54hG0byYHHHkNgBlgd+Ht/63SiXf1H6EFEwJsDoaGALOxhgOjF35wXAA3Slirbuidj68gUQ/wVQJmHK1Ctjbq7ypsYGupw+yZHeDoLVyr0//UrgYyG3nTAdLW1h6dxy30Ao07q9/vQ3LYJ6BQgqkt+ezsbr9m0Gy0wGf8de5W+FEd6gAB8aq1GRrSrL+P2ASFjo5LBwKFKcd4duiW5BRuxyrLUbMj8bLfDcPBAt+/QH/xZqB0jwzCVlN0y8R6FDdq/w6Amsg8AacsC2UsuiNB93tPf/oVKiUtJ9rVgQW66bQlxB9iW41iSAt0jC67N9SCbDYbC2A=
